###

GET http://localhost:3000/student
###

GET http://localhost:3000/student?name=John34
###

POST http://localhost:3000/student
Content-Type: application/json
    
    {
        "name": "John34",
        "age": 20,
        "_id": "022223336"
    }

###

PUT http://localhost:3000/student

###

DELETE  http://localhost:3000/student

