###

GET http://localhost:3000/student/
###

GET http://localhost:3000/student/022223336
###

POST http://localhost:3000/student
Content-Type: application/json
    
    {
        "name": "raphael",
        "age": 20,
        "_id": "02213336"
    }

###

PUT http://localhost:3000/student/022223336
Content-Type: application/json
    
    {
        "name": "Johny 677",
        "age": 29,
        "_id": "022223336"
    }

###

DELETE  http://localhost:3000/student

